language: node_js
sudo: required
node_js:
  - 8
services:
  - docker
before_install:
  - docker pull consul
  - docker run -d -p 8500:8500 -p 8600:53 -p 8400:8400 consul agent -dev -client 0.0.0.0 -advertise 127.0.0.1
  - docker ps -a
script:
  - yarn test
deploy:
  provider: npm
  email: mg@localz.co
  api_key:
    secure: pCxXfaqX+QD3JtuOIRoguDNdTRzJMLujnQuSVkgdChBhEsTfCPvyJpKa05JAA1JA1AlWmfoWP9mi+Notjsc46yVynk5tBM6kEeGFKdWVU4Aoi45e2X3ZCnBrSpM8RWXpV8eLv1xpi8rGlaau93lCSIXNa2uz0crvZ5j7ZeDe9iXZImNivvSquD3N6VEkY7nV1twt84f5ISAZ97IGw0H9XXbvup2h/E4l0rpoeASkh2YJ8vbYhzwMUcW5cjJ6sxNs7Xq3xbXY9kBpzPY3KtenMiKi3KfaqYa1XdTUdpcAYDdmHf75kpRKTB4rQ5KtXJRw+GQAkIyKrh1sIXBeYk8m4iw8piav1jZ3k2mF1X2yJuiU5ybo5LuGaJnl347q/SsffDKwLcdq2sy3kOTm6khgltEHsqwQ1MA+AJsilEfTZfgTuzqGE8fTE5/u/SMvIsOD8/WgHBOPsfUIiuGMJF7kDQu2/2HI5KYcHU6bC4ZZHhWU2nyab7MhKKh57Ei7ZXnVZJ11E2wnlGzdRO6r2j69fL7Z6BG6FzrgP3p47iPfd+ihiU8Dl+ym2rp1OZWzZuOVLUr2+zV/Z9Y+3AW1KYLrr4l7Ip0JcsIqFFSZUrukIRRvKK5pLthIUn5TnOrH7hCGFCtwP4I0KMFfOK926cNfOALnkExF3XhrMenwtuXhCzE=
  on:
    tags: true
    branch: master
    repo: localz/consul-backup-restore
